# Generated by Django 5.0.1 on 2024-04-07 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='hiring',
            name='company',
        ),
    ]
