# Generated by Django 5.0.1 on 2024-04-08 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0002_delete_event_remove_hiring_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring',
            name='company',
            field=models.ForeignKey(default='Shopify', on_delete=django.db.models.deletion.DO_NOTHING, related_name='hiring_set', to='dcs_app.comp_reg'),
        ),
    ]
