# Generated by Django 5.0.1 on 2024-04-08 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0003_hiring_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='company',
            field=models.ForeignKey(default='Shopify', on_delete=django.db.models.deletion.DO_NOTHING, to='dcs_app.comp_reg'),
        ),
    ]
