# Generated by Django 5.0.1 on 2024-04-10 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0008_alter_hiring_job_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiring',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='hiring',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hiring',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
