# Generated by Django 5.0.1 on 2024-04-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0009_alter_hiring_options_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
