# Generated by Django 5.0.1 on 2024-04-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0010_alter_hiring_created_alter_hiring_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_category',
            name='category_charge',
            field=models.IntegerField(default=50000),
        ),
        migrations.CreateModel(
            name='Employee_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=10)),
                ('response', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dcs_app.employee_reg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dcs_app.user_reg')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
