# Generated by Django 5.0.1 on 2024-04-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0011_employee_category_category_charge_employee_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_booking',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
