# Generated by Django 5.0.1 on 2024-04-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0012_alter_employee_booking_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_booking',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
    ]
