# Generated by Django 5.0.1 on 2024-04-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0013_alter_employee_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_booking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_reg',
            name='emp_phone',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
