# Generated by Django 5.0.1 on 2024-04-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0014_alter_employee_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='job_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='js_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
