# Generated by Django 5.0.1 on 2024-04-12 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0015_alter_hiring_job_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('resolve', models.TextField(null=True)),
                ('complaint_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('resolve_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('com_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dcs_app.employee_reg')),
                ('com_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dcs_app.user_reg')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
