# Generated by Django 5.0.1 on 2024-04-12 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0017_remove_complaint_com_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dcs_app.employee_booking'),
        ),
    ]
