# Generated by Django 5.0.1 on 2024-04-13 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0018_alter_complaint_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_booking',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolve_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
