# Generated by Django 5.0.1 on 2024-04-13 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0020_alter_feedback_options_remove_feedback_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dcs_app.employee_booking'),
        ),
    ]
