# Generated by Django 5.0.1 on 2024-04-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0022_alter_feedback_created_alter_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_booking',
            name='payment',
            field=models.FileField(default='', upload_to='Dailychores_Security/Payment_Screenshots/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(default='★★★★★', max_length=10),
        ),
    ]
