# Generated by Django 5.0.4 on 2024-06-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0024_alter_employee_booking_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='js_city',
            field=models.CharField(default='Lucknow', max_length=30),
        ),
    ]
