# Generated by Django 5.0.4 on 2024-06-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0025_jobapplication_js_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
