# Generated by Django 5.0.6 on 2024-06-25 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcs_app', '0027_comp_reg_usertype_user_reg_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('rating', models.CharField(default='★★★★★', max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dcs_app.user_reg')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
